# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Metascience
email: keenon@stanford.edu
description:
   Where I write about my lessons learned as an AI researcher trying to start a company.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keenon.github.io" # the base hostname & protocol for your site
# twitter_username: keenon
github_username:  keenon

# Build settings
markdown: kramdown
