# Site settings
title: Metascience
email: keenon@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Lessons learned as an AI researcher goes out and tries to start a company
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keenon.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  keenon

# Build settings
markdown: kramdown
