# Site settings
title: Metascience
email: keenon@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Ideas about improving cooperation, process, and productivity in computer science research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://keenon.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  keenon

# Build settings
markdown: kramdown
